query findPrescriptions($input: FindPrescriptionsInput!) {
  findPrescriptions(input: $input) {
    ok
    error
    prescriptions {
      id
      name
      requiredTime
      description
      price
      activate
      prescriptionAtoms {
        id
        name
      }
    }
  }
}
