import { CREATE_ATOM_PRESCRIPTION_DOCUMENT } from './createAtomPrescriptionGql';
import { CREATE_PRESCRIPTION_DOCUMENT } from './createPrescriptionGql';
import { EDIT_PRESCRIPTION_DOCUMENT } from './editPrescriptionGql';
import { FIND_ATOM_PRESCRIPTIONS_DOCUMENT } from './findAtomPrescriptionsGql';
import { FIND_PRESCRIPTIONS_DOCUMENT } from './findPrescriptionsGql';
import {
  ALL_PRESCRIPTION_FIELDS,
  COMMON_PRESCRIPTION_FIELDS,
} from './_prescriptionsFragmentsGql';

export {
  CREATE_ATOM_PRESCRIPTION_DOCUMENT,
  CREATE_PRESCRIPTION_DOCUMENT,
  EDIT_PRESCRIPTION_DOCUMENT,
  FIND_ATOM_PRESCRIPTIONS_DOCUMENT,
  FIND_PRESCRIPTIONS_DOCUMENT,
  ALL_PRESCRIPTION_FIELDS,
  COMMON_PRESCRIPTION_FIELDS,
};
