import { CREATE_ATOM_PRESCRIPTION_DOCUMENT } from './createAtomPrescription.gql';
import { CREATE_PRESCRIPTION_DOCUMENT } from './createPrescription.gql';
import { EDIT_PRESCRIPTION_DOCUMENT } from './editPrescription.gql';
import { FIND_ATOM_PRESCRIPTIONS_DOCUMENT } from './findAtomPrescriptions.gql';
import { FIND_PRESCRIPTIONS_DOCUMENT } from './findPrescriptions.gql';
import {
  ALL_PRESCRIPTION_FIELDS,
  COMMON_PRESCRIPTION_FIELDS,
} from './_prescriptionsFragments.gql';

export {
  CREATE_ATOM_PRESCRIPTION_DOCUMENT,
  CREATE_PRESCRIPTION_DOCUMENT,
  EDIT_PRESCRIPTION_DOCUMENT,
  FIND_ATOM_PRESCRIPTIONS_DOCUMENT,
  FIND_PRESCRIPTIONS_DOCUMENT,
  ALL_PRESCRIPTION_FIELDS,
  COMMON_PRESCRIPTION_FIELDS,
};
