query getStatistics($input: GetStatisticsInput!) {
  getStatistics(input: $input) {
    error
    ok
    prescriptions {
      id
      name
      price
      requiredTime
    }
    visitRates {
      patientId
      visited
    }
    dailyReports {
      date
      reservationCount
      noshow
      cancel
      newPatient
      users {
        userId
        reservationCount
        noshow
        cancel
        newPatient
        visitMoreThanThirty
        visitMoreThanSixty
        visitMoreThanNinety
        prescriptions {
          id
          name
          count
        }
        reservations {
          id
          startDate
          endDate
          state
          memo
          isFirst
          prescriptions {
            id
            name
            price
            requiredTime
          }
          patient {
            id
            name
          }
          lastModifier {
            id
            name
          }
        }
      }
    }
  }
}
