query getClinic($input: GetClinicInput!) {
  getClinic(input: $input) {
    ok
    error
    clinic {
      id
      name
      members {
        id
        staying
        manager
        accepted
        user {
          id
          name
          email
        }
      }
    }
  }
}
